java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output1.out experiment1/inputs1.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output2.out experiment1/inputs2.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output3.out experiment1/inputs3.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output4.out experiment1/inputs4.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output5.out experiment1/inputs5.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output6.out experiment1/inputs6.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output7.out experiment1/inputs7.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output8.out experiment1/inputs8.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output9.out experiment1/inputs9.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output10.out experiment1/inputs10.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output11.out experiment1/inputs11.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output12.out experiment1/inputs12.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output13.out experiment1/inputs13.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output14.out experiment1/inputs14.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output15.out experiment1/inputs15.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output16.out experiment1/inputs16.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output17.out experiment1/inputs17.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output18.out experiment1/inputs18.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output19.out experiment1/inputs19.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output20.out experiment1/inputs20.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output21.out experiment1/inputs21.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output22.out experiment1/inputs22.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output23.out experiment1/inputs23.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output24.out experiment1/inputs24.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output25.out experiment1/inputs25.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output26.out experiment1/inputs26.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output27.out experiment1/inputs27.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output28.out experiment1/inputs28.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output29.out experiment1/inputs29.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output30.out experiment1/inputs30.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output31.out experiment1/inputs31.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters1.prp experiment1/IdealSJFScheduler_output32.out experiment1/inputs32.in