java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output1.out experiment1/inputs1.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output2.out experiment1/inputs2.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output3.out experiment1/inputs3.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output4.out experiment1/inputs4.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output5.out experiment1/inputs5.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output6.out experiment1/inputs6.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output7.out experiment1/inputs7.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output8.out experiment1/inputs8.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output9.out experiment1/inputs9.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output10.out experiment1/inputs10.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output11.out experiment1/inputs11.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output12.out experiment1/inputs12.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output13.out experiment1/inputs13.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output14.out experiment1/inputs14.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output15.out experiment1/inputs15.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output16.out experiment1/inputs16.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output17.out experiment1/inputs17.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output18.out experiment1/inputs18.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output19.out experiment1/inputs19.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output20.out experiment1/inputs20.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output21.out experiment1/inputs21.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output22.out experiment1/inputs22.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output23.out experiment1/inputs23.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output24.out experiment1/inputs24.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output25.out experiment1/inputs25.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output26.out experiment1/inputs26.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output27.out experiment1/inputs27.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output28.out experiment1/inputs28.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output29.out experiment1/inputs29.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output30.out experiment1/inputs30.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output31.out experiment1/inputs31.in
java -cp target/os-coursework1-1.0-SNAPSHOT.jar Simulator experiment1/simulator_parameters4.prp experiment1/SJFScheduler_output32.out experiment1/inputs32.in
